//! Everything has an identity, let's deal with that…
use std::fmt::Display;

pub mod uniq;

pub const MAX_ID_LEN: usize = 255;

/// Various ID related errors…
#[derive(Debug, PartialEq, Clone)]
pub enum IdError {
    /// Input was entirely non-alphanum (or empty).
    EmptyOrGarbage,
    /// Input too long (for e.g. file system).
    TooLong,
    /// Input contains forbidden/reserved (e.g. any of the hardcoded bootstrap)
    /// patterns or is otherwise "unusable".
    ReservedName(String),
    /// Password mismatch…
    PasswordMismatch,
}

impl Display for IdError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::EmptyOrGarbage => write!(f, "Well, identity contains no readable alphanum characters. Might want to rething that…"),
            Self::ReservedName(n) => write!(f, "Sorry, but '{}' is already reserved by the system itself…", n),
            Self::TooLong => write!(f, "For file system sanity reasons the input was considered 'too long' (in excess of {} characters). Cut it down a bit, ok?", MAX_ID_LEN),
            Self::PasswordMismatch => write!(f, "Password mismatch…"),
        }
    }
}

impl std::error::Error for IdError {}

/// A trait for anything and everything with "identity".
pub trait IdentityQuery {
    /// Get the ID.
    fn id<'a>(&'a self) -> &'a str;
    /// Get the title/name.
    fn title<'a>(&'a self) -> &'a str;
}

pub type MachineId = usize;

pub trait MachineIdentity {
    fn as_m_id(&self) -> MachineId;
}

impl MachineIdentity for str {
    fn as_m_id(&self) -> MachineId {
        use std::collections::hash_map::DefaultHasher;
        use std::hash::{Hash, Hasher};
        let mut s = DefaultHasher::new();
        self.hash(&mut s);
        s.finish() as MachineId
    }
}

/// A trait for anything and everything with mutable "identity".
pub trait IdentityMut : IdentityQuery {
    /// Safely set ID, if possible.
    /// Given `value` will be ran through [as_id\(\)][crate::identity::uniq::as_id] check
    /// if `is_m_id` isn't set to `true`.
    /// 
    /// # Args
    /// - `value` to use as ID.
    /// - `is_m_id` indicates if the ID is pregenerated by the engine.
    fn set_id(&mut self, value: &str, is_m_id: bool) -> Result<(), IdError>;

    /// Get ref to raw title/name.
    fn title_mut<'a>(&'a mut self) -> &'a mut String;
    /// Safely set title to `value`.
    // Convenience method really as titles in general are freeform, and thus lack validation.
    fn set_title(&mut self, value: &str);
}

#[cfg(test)]
mod identity_tests {
    use cosmic_garden_pm::IdentityMut;

    use super::*;

    #[derive(IdentityMut)]
    struct Identifiable {
        id: String,
        #[identity(title)]
        nomnom: String,
    }

    #[test]
    fn identity_query_derive() {
        let i = Identifiable { id: "<an id>".into(), nomnom: "<a title>".into() };
        assert_eq!("<an id>", i.id());
        assert_eq!("<a title>", i.title());
    }

    #[test]
    fn identity_mut_derive() {
        let mut i = Identifiable { id: "<an id>".into(), nomnom: "<a title>".into() };
        // machine pregenerated ID…
        _ = i.set_id("<a mutant id>", true);
        *i.title_mut() = "<a mangy title>".into();
        assert!(i.id().starts_with("<a mutant id>"));
        assert_eq!("<a mangy title>", i.title());
        // human input ID source
        _ = i.set_id("<a mutant id>", false);
        assert!(i.id().starts_with("a-mutant-id-"));
    }

    #[test]
    fn identity_mut_push() {
        let mut i = Identifiable { id: "<an id>".into(), nomnom: "<a title>".into() };
        i.title_mut().push_str(" is broken…");
        *i.title_mut() = i.title().replace("<a", "<t3h");
        assert_eq!("<t3h title> is broken…", i.title());
    }
}
